#!/bin/zsh

# Keybindings
# vi keybindings
bindkey -v

# do history expansion on space
bindkey ' ' magic-space
# delete
bindkey '^[[3~' delete-char
# page up
bindkey '^[[5~' beginning-of-buffer-or-history
# page down
bindkey '^[[6~' end-of-buffer-or-history

# file manager cd
bindkey -s '^[/' 'fmcd\n'
# fuzzy finder cd
bindkey -s '^[?' 'ffcd\n'
