#!/bin/zsh

# Keybindings
# vi keybindings
bindkey -v

# do history expansion on space
bindkey ' ' magic-space
# delete
bindkey '^[[3~' delete-char
# page up
bindkey '^[[5~' beginning-of-buffer-or-history
# page down
bindkey '^[[6~' end-of-buffer-or-history

# lfcd - ctrl-o
bindkey -s '^\' 'lfcd\n'
# fzfcd - ctrl-/ (terminals may not distinguish between ctrl-/ and ctrl-_)
bindkey -s '^_' 'fzfcd\n'
