#!/bin/zsh

# Environment variables are set here.
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/environmentrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/environmentrc
else
	command echo "environmentrc could not be found"
fi
