#!/bin/zsh

# Config for zsh interactive shells

# Security
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/securityrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/securityrc
fi

# Plugins:
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh/pluginrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh/pluginrc
fi

# Security
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/securityrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/securityrc
fi

# ZSH-specific settings
setopt autocd								# change directory just by typing its name
setopt interactivecomments	# allow comments in interactive mode
setopt magicequalsubst			# enable filename expansion for arguments of the form ‘anything=expression’
setopt notify								# report the status of background jobs immediately
setopt numericglobsort			# sort filenames numerically when it makes sense
setopt promptsubst	# command substitution in the prompt

# history configurations
setopt hist_expire_dups_first			# delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups					# ignore duplicated commands history list
setopt hist_ignore_space				# ignore commands that start with space
setopt hist_verify						# show command with history expansion to user before running it
setopt share_history					# share command history data

# ZSH-specific variables
# don't consider certain characters part of the word
WORDCHARS=${WORDCHARS//\/}

# configure `time` format
TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S\ncpu\t%P'

# history configurations
HISTFILE=~/.local/state/zsh-history
HISTSIZE=10000000
SAVEHIST=20000000

# Take advantage of colors ($LS_COLORS for completion as well)
if [ -x /usr/bin/dircolors ]; then
	[ -r ~/.dircolors ] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	# begin blink
	export LESS_TERMCAP_mb=$'\E[1;31m'
	# begin bold
	export LESS_TERMCAP_md=$'\E[1;36m'
	# reset bold/blink
	export LESS_TERMCAP_me=$'\E[0m'
	# begin reverse video
	export LESS_TERMCAP_so=$'\E[01;33m'
	# reset reverse video
	export LESS_TERMCAP_se=$'\E[0m'
	# begin underline
	export LESS_TERMCAP_us=$'\E[1;32m'
	# reset underline
	export LESS_TERMCAP_ue=$'\E[0m'

	zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
	zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
fi

# Enable completion features
autoload -Uz compinit
compinit -d ~/.cache/zcompdump
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' rehash true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Shell builitin commands help
autoload run-help
HELPDIR=/usr/share/zsh/"${ZSH_VERSION}"/help
alias help=run-help

# Prompt configuration
# configure a colored prompt
configure_prompt() {
	PROMPT=$'%B%F{%(#.white.white)}┌──(%F{%(#.red.red)}%n@%m%F{%(#.white.white)})%b-%B[%F{reset}%(6~.%-1~/…/%4~.%5~)%F{%(#.white.white)}]\n└──%(#.%F{red}( # %).%F{white}(%F{red} $ %F{white}%))%b%F{reset} '

	RPROMPT=$'%(?.. %? %F{red}%Bx%b%F{reset})%(1j. %j %F{yellow}%B⚙%b%F{reset}.)'
}

configure_prompt

# set a colorless prompt (only uncomment the next line if necessary)
# PROMPT='$%n@%m:%~%# '

# print a new line before the prompt, but only if it is not the first line
precmd() {
	if [ -z "$NEW_LINE_BEFORE_PROMPT" ]; then
		NEW_LINE_BEFORE_PROMPT=1
	else
		command echo
	fi
}

# hide EOL sign ('%')
PROMPT_EOL_MARK=""

# change cursor shape for different vi modes.
function zle-keymap-select () {
	case $KEYMAP in
		vicmd) command echo -ne '\e[1 q';;      # block
		viins|main) command echo -ne '\e[5 q';; # beam
	esac
}

zle -N zle-keymap-select

# use beam shape cursor on startup
command echo -ne '\e[5 q'

# use beam shape cursor for each new prompt
preexec() {
	command echo -ne '\e[5 q'
}

# Tab width
command tabs -4

# Load keybindings if existent
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/keybindingrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/keybindingrc
fi

# Load aliases if existent
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/aliasrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/aliasrc
fi

# Load functions if existent
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/functionrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/functionrc
fi
