#!/bin/sh

# Notification Server
pidof -sx dunst || dunst &

# Display setup
autorandr --change

# Compositor
pidof -sx picom || picom &

# Wallpaper
feh --no-fehbg --randomize --bg-fill "$HOME"/pictures/wallpapers/gruvbox

# Keyboard layout modifications
xmodmap ~/.config/xmodmap

# Internet connection applet
pidof -sx nm-applet || nm-applet &

# Display temperature
displaytemperature -n default

# Disable DPMS
xset -dmps
