#!/bin/sh

# Notification Server
pidof -sx dunst || dunst &

# Display setup
autorandr --change

# Compositor
pidof -sx picom || picom &

# Internet connection applet
pidof -sx nm-applet || nm-applet &

# Disable DPMS
xset -dpms
xset s off
