#!/bin/sh

# Notification Server
pidof -sx dunst || dunst &

# Wallpaper
feh --no-fehbg --randomize --bg-fill "$HOME"/pictures/wallpapers/gruvbox

# Keyboard layout modifications
xmodmap ~/.config/xmodmap

# Internet connection applet
pidof -sx nm-applet || nm-applet &

# Display setup
displayctl -n dual

# Compositor
pidof -sx picom || picom &

# Display temperature
displaytemperature -n default
