#!/bin/sh

# file operations
alias ls='command ls -l'
alias la='ls -A'
alias cp='command cp -i'
alias mv='command mv -i'
alias rsync='command rsync -Prluv'

# networking
alias ip="command ip -c=auto"

# editor
alias v="$EDITOR"

# abook
alias abook='command abook --config "${XDG_CONFIG_HOME:-$HOME/.config}"/abook/abookrc --datafile "$HOME"/personal/abook/addressbook'

# mbsync
alias mbsync='command mbsync --config "${PERSONAL_DATA_HOME:-$HOME/personal}"/isync/mbsyncrc'

# vim keybindings
alias vkb='command xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}"/xmodmap || command  sudo loadkeys "${XDG_CONFIG_HOME:-$HOME/.config}"/ttykeymap'

# exa (override ls if exa is installed)
if command -v exa 1>/dev/null 2>&1; then
	alias ls='command exa -lghF --group-directories-first --git --icons --color=automatic'
	alias la='ls -a'
	alias lt='ls --time-style=long-iso'
	alias lta='lt -a'
fi

# personal aliases
. "${XDG_CONFIG_HOME:-$HOME/.config}"/nqpnqs/shell/aliasrc
