#!/bin/sh

# Additions to $PATH:
export PATH="$PATH:$HOME"/.local/bin
#export PATH="$PATH:$HOME"/.local/go/bin

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="librewolf"
# sudo's askpass has to be set with an absolute path
SUDO_ASKPASS="$(command -v dmenupass)"
export SUDO_ASKPASS
# if bat is installed, use it to display man pages
if command -vp bat 1>/dev/null 2>&1; then
	export MANPAGER="sh -c 'col -bx | command bat -l man -p'"
	export MANROFFOPT="-c"
fi

# User directories:
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.cache

# Shells:
# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
# Readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

# Programming languages:
#Rust
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
#Go
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
#Python
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME"/python
export PYTHONUSERBASE="$XDG_DATA_HOME"/python

# Programs:
# GPG
export GNUPGHOME="$HOME"/.gnupg
# Ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/ripgreprc
# Wget
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc

# GTK
export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
