#!/bin/sh

# Additions to $PATH:
export PATH="$PATH:$HOME"/.local/bin

# Default programs:
if command -v nvim 1>/dev/null 2>&1; then
	EDITOR="$(command -v nvim)"
	export EDITOR
else
	EDITOR="$(command -v vi)"
	export EDITOR
fi
TERMINAL="$(command -v alacritty)"
export TERMINAL
BROWSER="$(command -v librewolf)"
export BROWSER
# sudo's askpass has to be set with an absolute path
SUDO_ASKPASS="$(command -v dmenuaskpass)"
export SUDO_ASKPASS
# if bat is installed, use it to display man pages
if command -v bat 1>/dev/null 2>&1; then
	export MANPAGER="sh -c 'col -bx | command bat -l man -p'"
	export MANROFFOPT="-c"
fi

# XDG user directories:
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.cache

# Personal user directories:
export USER_BIN_HOME="$HOME"/.local/bin

# Shells:
# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
# Bash
export BASH_ENV="$XDG_CONFIG_HOME"/bash/bash-profile
# Readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc

# Programming languages:
#Rust
export CARGO_HOME="$HOME"/.cargo
export RUSTUP_HOME="$HOME"/.rustup
#Go
export GOPATH="$XDG_DATA_HOME"/go
export GOBIN="$USER_BIN_HOME"
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
#Python
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME"/python
export PYTHONUSERBASE="$XDG_DATA_HOME"/python

# Programs:
# GPG
export GNUPGHOME="$HOME"/.gnupg
# Ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/ripgreprc
# Wget
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc

# GTK
export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
