#!/bin/sh

# POSIX-compliant-syntax functions meant for use in interactive shells.

# Use lf to switch directories
lfcd () {
	\umask 077

	tmp="$(command mktemp)"
	command lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
		dir="$(command cat "$tmp")"
		command rm -f "$tmp"
	else
		\return 1
	fi
	if [ -d "$dir" ] && [ "$dir" != "$(pwd)" ]; then
		\cd "$dir" || \return 1
	fi
}

# image viewer that cycles through all the images in the current directory
imgv () {
	file=''
	if [ -f "$1" ];then
		file="$1"
		shift 1
	fi
	command rotdir "$file" | command nsxiv -i "$@" 2>/dev/null
	unset -v file
}

# git config files
config () {
	command git --git-dir="$HOME"/.configuration/ --work-tree="$HOME" "$@"
}
