#!/bin/sh

# POSIX-compliant-syntax functions meant for use in interactive shells.

# Use lf to switch directories
lfcd () {
	\cd "$(command lf -print-last-dir "$@")" || return 1
}

ffcd () {
	\cd "$(find . -type d -name "*" -print | fzf --scheme=path "$@")" || return 1
}

# image viewer that cycles through all the images in the current directory
imgv () {
	file=''
	if [ -f "$1" ];then
		file="$1"
		shift 1
	fi
	command rotdir "$file" | command nsxiv -i "$@" 2>/dev/null
	unset -v file
}

# git config files
config () {
	command git --git-dir="$HOME"/.configuration/ --work-tree="$HOME" "$@"
}
