#!/bin/sh

# Notification Server
pidof -sx dunst || dunst &

# Display setup
displayctl -n dual 1>/var/log/nick/displayctl 2>&1

# Compositor
pidof -sx picom || picom &

# Wallpaper
feh --no-fehbg --randomize --bg-fill "$HOME"/pictures/wallpapers/gruvbox

# Keyboard layout modifications
xmodmap ~/.config/xmodmap

# Internet connection applet
pidof -sx nm-applet || nm-applet &
