#!/bin/sh

# Notification Server
dunst &

# Display setup
displayctl -n dual 1>/var/log/nick/displayctl 2>&1

# Compositor
picom &

# Wallpaper
feh --no-fehbg --randomize --bg-fill "$HOME"/pictures/wallpapers/gruvbox

# Keyboard layout modifications
xmodmap ~/.config/xmodmap

# Internet connection applet
nm-applet &
