[general]
live_config_reload = false

[env]
TERM = "alacritty"

[window]
decorations = "Full"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.position]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = false

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#fe8019'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.cursor]
cursor = "#ffffff"
text = "#282828"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

# [colors.hints.start]
# background = "#e9ff5e"
# foreground = "#1d1f21"
# 
# [colors.hints.end]
# background = "#1d1f21"
# foreground = "#e9ff5e"
# 
# [colors.search.matches]
# background = "#504945"
# foreground = "#ebdbb2"
# 
# [colors.search.focused_match]
# background = "#fe8019"
# foreground = "#282828"
# 
# [colors.selection]
# background = "CellForeground"
# text = "CellBackground"
# 
# [colors.vi_mode_cursor]
# cursor = "#ffffff"
# text = "#282828"

[cursor]
thickness = 0.15
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[[keyboard.bindings]]
# Delete word backward
mods = "Control"
key = "Back"
chars = "\u0017"

[[keyboard.bindings]]
# Delete line backward
mods = "Shift|Control"
key = "Back"
chars = "\u0015" 

[[keyboard.bindings]]
mode = "~Search"
mods = "Shift|Control"
key = "Escape"
action = "ToggleViMode" 

[[keyboard.bindings]]
mode = "Vi|~Search"
key = "Escape"
action = "ClearSelection" 
