#!/bin/bash

# Config for bash interactive shells

# Environment variables
. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/environmentrc

# If not running interactively, don't do anything else
if [[ $- != *i* ]]; then
	return 0
fi

# Interactive shell prompt
PS1='(\u@\h)-[\W]-( \$ ) '
PS2='> '
PROMPT_COMMAND="command echo"

# History configuration
HISTFILE="$XDG_STATE_HOME"/bash/history

# Baseline
. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/baselinerc

# Load aliases
. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/aliasrc

# Load functions
. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/functionrc

# Keybindings
# vi keybindings
set -o vi
# ctrl-l clear
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

#lfcd
bind -m vi-insert '"\C-_":"lfcd\C-m"'
