#!/bin/bash

# Config for bash interactive shells

# Baseline
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/baselinerc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/baselinerc
else
	command echo "Baseline couldn't be set." 1>&2
fi

# If not running interactively, don't do anything
if [[ $- != *i* ]]; then
	return 0
fi

# Environment variables
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/environmentrc ];then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/environmentrc
fi

# Interactive shell prompt
PS1='(\u@\h)-[\W]-( \$ ) '
PS2='> '
PROMPT_COMMAND="command echo"

# History configuration
HISTFILE="$XDG_STATE_HOME"/bash/history

# Tab width
command tabs -4

# Load aliases if existent
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/aliasrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/aliasrc
fi

# Load functions if existent
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/functionrc ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/functionrc
fi

# keybindings
set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'
