#!/bin/sh

# Default programs:
if command -v nvim 1>/dev/null 2>&1; then
	EDITOR="$(command -v nvim)"
	export EDITOR
else
	EDITOR="$(command -v vi)"
	export EDITOR
fi
TERMINAL="$(command -v alacritty)"
export TERMINAL
BROWSER="$(command -v chromium)"
export BROWSER
# if bat is installed, use it to display man pages
if command -v bat 1>/dev/null 2>&1; then
	export MANPAGER="sh -c 'col -bx | command bat -l man -p'"
	export MANROFFOPT="-c"
fi

# User directories:
# XDG user directories
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.cache
# Personal user directories
export PERSONAL_KEYS_HOME="$HOME"/0-keys

# Programs:
# Readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
# Ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/ripgreprc
# Wget
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc

# Additions to $PATH:
export PATH="$PATH:$XDG_CONFIG_HOME"/emacs/bin
